#!/usr/bin/env python3
"""Regenerate _includes/sea-map.html: a static SVG map of Seeing Culture coverage.

Static SVG on purpose. A mapping library (Leaflet, D3 + topojson) would be tens
of kilobytes of JavaScript to draw eleven fixed shapes that never move.

Country shapes come from Natural Earth 110m, simplified with Douglas-Peucker.
Coverage numbers come from the benchmark's own MCQ_List.csv, so the map cannot
drift from the dataset:

    curl -sL https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson -o /tmp/world.geojson
    curl -sL https://huggingface.co/datasets/Multimedia-SMU/seeingculture-benchmark/resolve/main/mcq_data/MCQ_List.csv -o /tmp/mcq.csv
    python3 scripts/make_sea_map.py
"""
import collections
import csv
import io
import json
import os

WORLD = os.environ.get("WORLD_GEOJSON", "/tmp/world.geojson")
MCQ = os.environ.get("MCQ_CSV", "/tmp/mcq.csv")
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "_includes", "sea-map.html")

# Every Southeast Asian country is drawn; the ones in the benchmark are filled.
SEA = ["Indonesia", "Myanmar", "Thailand", "Vietnam", "Philippines", "Malaysia",
       "Cambodia", "Laos", "Brunei", "Timor-Leste"]
# Singapore has no polygon at 110m resolution, so it is drawn as a marker.
SINGAPORE = (103.82, 1.35)

LON0, LON1 = 91.0, 142.5
LAT0, LAT1 = -11.5, 29.0
W, H = 620.0, 480.0


def project(lon, lat):
    x = (lon - LON0) / (LON1 - LON0) * W
    y = (LAT1 - lat) / (LAT1 - LAT0) * H
    return x, y


def rdp(pts, eps):
    """Douglas-Peucker. Keeps the coastline readable at a fraction of the points."""
    if len(pts) < 3:
        return pts
    x0, y0 = pts[0]
    x1, y1 = pts[-1]
    dx, dy = x1 - x0, y1 - y0
    n = (dx * dx + dy * dy) ** 0.5
    worst, idx = 0.0, 0
    for i in range(1, len(pts) - 1):
        px, py = pts[i]
        if n == 0:
            d = ((px - x0) ** 2 + (py - y0) ** 2) ** 0.5
        else:
            d = abs(dy * px - dx * py + x1 * y0 - y1 * x0) / n
        if d > worst:
            worst, idx = d, i
    if worst <= eps:
        return [pts[0], pts[-1]]
    return rdp(pts[:idx + 1], eps)[:-1] + rdp(pts[idx:], eps)


def rings(geom):
    t, c = geom["type"], geom["coordinates"]
    if t == "Polygon":
        return [c[0]]
    if t == "MultiPolygon":
        return [poly[0] for poly in c]
    return []


def path_for(geom, eps=0.9, min_pts=4):
    out = []
    for ring in rings(geom):
        pts = [project(lon, lat) for lon, lat in ring]
        pts = [p for p in pts if -60 <= p[0] <= W + 60 and -60 <= p[1] <= H + 60]
        if len(pts) < min_pts:
            continue
        pts = rdp(pts, eps)
        if len(pts) < min_pts:
            continue
        d = "M" + " ".join("%.1f %.1f" % (x, y) for x, y in pts) + "Z"
        out.append(d)
    return " ".join(out)


# ---------------------------------------------------------------- coverage data
rows = list(csv.DictReader(io.open(MCQ, encoding="utf-8")))
qs = collections.Counter()
concepts = collections.defaultdict(set)
for r in rows:
    c = r["country"].strip()
    qs[c] += 1
    concepts[c].add(r["concept"].strip())
covered = {c: (qs[c], len(concepts[c])) for c in qs}
maxq = max(qs.values())

world = json.load(io.open(WORLD, encoding="utf-8"))
feats = {}
for f in world["features"]:
    n = f["properties"].get("NAME") or f["properties"].get("name")
    if n in SEA:
        feats[n] = f["geometry"]

missing = [c for c in SEA if c not in feats]
if missing:
    print("  WARNING: no geometry for %s" % ", ".join(missing))

parts = []
# Built with concatenation, not %-formatting: the Liquid braces below would be
# read as format specifiers.
HEADER = """{% comment %}
  Seeing Culture coverage, as a static SVG. Generated by scripts/make_sea_map.py
  from Natural Earth 110m geometry and the benchmark's own MCQ_List.csv, so the
  numbers here cannot drift from the dataset.

  No JavaScript and no mapping library: these are eleven fixed shapes. Each
  country carries a <title>, which browsers show as a tooltip and screen readers
  announce, and the figure below the map states the same numbers as text so the
  information does not depend on hover.
{% endcomment %}
<figure class="seamap">
  <svg class="seamap__svg" viewBox="0 0 __W__ __H__" role="img"
       aria-labelledby="seamap-title seamap-desc">
    <title id="seamap-title">Seeing Culture benchmark coverage across Southeast Asia</title>
    <desc id="seamap-desc">__DESC__</desc>"""

desc = "; ".join("%s %d questions across %d artifacts" % (c, qs[c], len(concepts[c]))
                 for c in sorted(qs, key=lambda x: -qs[x]))
parts.append(HEADER.replace("__W__", str(int(W))).replace("__H__", str(int(H)))
                   .replace("__DESC__", desc))

for name in SEA:
    if name not in feats:
        continue
    d = path_for(feats[name])
    if not d:
        continue
    if name in covered:
        q, a = covered[name]
        # opacity carries relative volume; the caption carries the actual numbers
        w = 0.30 + 0.70 * (float(q) / maxq) ** 0.55
        parts.append('    <path class="seamap__c is-covered" style="--w:%.2f" d="%s">'
                     '<title>%s: %d questions, %d artifacts</title></path>'
                     % (w, d, name, q, a))
    else:
        parts.append('    <path class="seamap__c" d="%s"><title>%s: not in the benchmark</title></path>'
                     % (d, name))

sx, sy = project(*SINGAPORE)
parts.append('    <circle class="seamap__pin" cx="%.1f" cy="%.1f" r="4">'
             '<title>Singapore: where the benchmark was built</title></circle>' % (sx, sy))
parts.append("  </svg>")

ordered = sorted(qs, key=lambda x: -qs[x])
parts.append('  <figcaption class="seamap__cap">')
parts.append('    <p class="seamap__lede"><strong>%d questions</strong> on <strong>%d cultural artifacts</strong> '
             'across <strong>%d countries</strong>, from the '
             '<a href="/publications/seeing-culture/">Seeing Culture</a> benchmark.</p>'
             % (len(rows), sum(len(v) for v in concepts.values()), len(qs)))
parts.append('    <ul class="seamap__list">')
for c in ordered:
    parts.append('      <li><span class="seamap__country">%s</span>'
                 '<span class="seamap__n">%d questions &middot; %d artifacts</span></li>'
                 % (c, qs[c], len(concepts[c])))
parts.append("    </ul>")
parts.append("  </figcaption>")
parts.append("</figure>")

io.open(OUT, "w", encoding="utf-8").write("\n".join(parts) + "\n")
print("wrote %s (%.1f KB)" % (OUT, os.path.getsize(OUT) / 1024.0))
print("countries drawn: %d (%d covered)" % (len(feats) + 1, len(covered)))
for c in ordered:
    print("  %-14s %5d questions  %3d artifacts" % (c, qs[c], len(concepts[c])))
